server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jiejie?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5

#配置输出日志，用于显示执行的sql语句
logging:
  level:
    root: info
    org.mybatis: debug
    com.baidu.testthymeleaf: debug

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.baidu.supermarket.pojo