#????????????
server:
  port: 8008
  tomcat:
    uri-encoding: UTF-8
springdoc:
  swagger-ui:
    path: /swagger-ui.html

#???????
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytest02?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML5

mybatis-plus:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.baidu.springboot07.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


